[package]
name = "owmods_gui"
authors = ["Bwc9876 <bwc9876@outerwildsmods.com>"]
description = "A GUI Tool To Manage OWML Mods"
version = "0.14.2"
readme = "./README.md"
repository = "https://github.com/ow-mods/ow-mod-man/"
license = "GPL-3.0-or-later"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.8", features = [] }

[dependencies]
owmods_core = { version = "0.12.0", path = "../../owmods_core" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-alpha", features = [] }
anyhow = "1.0.75"
tokio = { version = "1.32.0", features = ["sync", "macros"] }
log = { version = "0.4.20", features = ["std", "serde"] }
typeshare = "1.0.1"
notify = { version = "6.0.1", default-features = false, features = [
    "macos_kqueue",
] }
regex = "1.9.3"
time = { version = "0.3.25", features = ["macros", "local-offset"] }
tauri-plugin-deep-link = "0.1.2"
opener = "0.6.1"
tauri-plugin-window = "2.0.0-alpha.1"
tauri-plugin-dialog = "2.0.0-alpha.1"
tauri-plugin-updater = "2.0.0-alpha.1"
tauri-plugin-os = "2.0.0-alpha.1"
tauri-plugin-app = "2.0.0-alpha.1"
tauri-plugin-shell = "2.0.0-alpha.1"
tauri-plugin-clipboard-manager = "2.0.0-beta.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
